#!/usr/bin/env python3
"""
pbcreatespear <usergroup> <start-date>

TODO:
        - check the URLs provided to see that they match those we have
          i.e. secserv.kr and youepix.kr
        - get some actual 'at' jobs created
        - sort out date confusion

"""

import sys
from pbsettings import GOPHISH_KEY, URL
from pbos import schedule_spear_mailshots, show_schedule
from pbcalc import check_date, split_and_check
from pbgophish import (
    check_for_subgroups, check_group, check_templates, check_spear_templates, 
    check_spear_smtp_profiles, get_mailshot_data, check_scare_page, 
    get_num_spear_groups, create_sub
    )

def main():
    if len(sys.argv) < 2:
        sys.exit(
        "\n Usage: pbcreatespear <usergroup> "
        "\n "
        "\n e.g     pbcreatespear ACME0816 "
        "\n "
        "\n     Requires a series of groups named like:"
        "\n "
        "\n         ACME0816-spear-1 "
        "\n         ACME0816-spear-2 "
        )

    base_group = sys.argv[1]

    #   Check that everthing is fine
    base_group_object=check_group(base_group)
    spears = get_num_spear_groups(base_group)
    check_spear_templates(base_group, spears)
    check_spear_smtp_profiles(base_group,spears)
    check_scare_page(base_group)

    #   Schedule the mailshots via a little 'hack' where we get the timing and 
    #   URL from text in the the 'position' field of the first member of the 
    #   spear group; in this format:
    #
    #       dd/mm/yyyy hh:mm URL
    #
    #   e.g.:
    #
    #       28/11/2016 16:15 http://dropbox.secserv.kr/0098098.jpg
    #
    spear_names = []
    mailshot_params = []

    for spear in range(spears):
        spear_names.append(base_group + "-spear-" +str(spear))
        mailshot_data = (get_mailshot_data(spear_names[spear]))
        mailshot_params.append(split_and_check(mailshot_data))

    #   Now schedule the mailshots...
    schedule_spear_mailshots(base_group, spear_names, mailshot_params)
    show_schedule(base_group)

# ------- supporting functions are defined below -------------------------


if __name__ == '__main__':
    sys.exit(main())
