#!/usr/bin/env python3
"""
pbkill <usergroup> 

    Kill only the queued 'at' jobs related to one basegroup

    e.g pbkill ACME0816

TODO:
    - fix some repeating weirdness...

"""
import sys

from pbgophish import get_at_jobs
from pbgophish import group_name
from pbgophish import kill_job


def main():
    if len(sys.argv) < 2:
        sys.exit(
            "\n Usage: pbkill <basegroup> "
            "\n "
            "\n e.g     pbkill ACME0816 (which will kill all matching 'at' tasks) "
            "\n "
        )

    base_group = sys.argv[1]
    jobs = get_at_jobs()
    found = False

    for job in jobs:
        # print("Checking task: ", job, "...")
        if base_group in group_name(job):
            found += 1
            kill_job(job)
            print("[OK] Killed job ", job)
    if found:
        print("\nKilled ", found, "tasks")
    else:
        print("\nNo matching tasks found")


if __name__ == '__main__':
    sys.exit(main())
