#!/usr/bin/env python3 
#
"""This will create a campaign with a specific start date. It is normally
    called by "pbcreateplan", and trusts that to have checked stuff - so
    does no more checking...
"""

import sys
import requests

def main():
    import json
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText
    import smtplib
    from pbsettings import PHISH_MASTER, EMAIL_FROM, URL, GOPHISH_KEY
    from pbgophish import create_camp

    if len(sys.argv) < 7:
        sys.exit(
            "\n Usage: pbschedulecampaign <name> <template> <page> <url> <smtp> <groups>"
            "\n "
        )

    '''
        {
        "name":"CC Example Campaign",
        "template":{"name":"Example Template"},
        "url":"http://localhost",
        "page":{"name":"Example Landing Page"},
        "smtp":{"name":"Example Sending Profile"},
        "launch_date":"2018-10-08T16:20:00+00:00",
        "send_by_date":null,
        "groups":[{"name":"Example Group"}]
        }
    '''

    o_data = {"name": sys.argv[1],
              "template": {"name": sys.argv[2]},
              "page": {"name": sys.argv[3]},
              "url": sys.argv[4],
              "smtp": {"name": sys.argv[5]},
              "launch_date":"2019-04-25T20:17:00Z",
              "send_by_date":"0001-01-01T00:00:00Z",
              "groups": [{"name": sys.argv[6]}]
              }
    n_data = json.dumps(o_data)

    #   Now create the new campaign
    resp = create_camp(n_data)

    name=sys.argv[1]
    # then try to find and dump it... 
    print("Looking for ", name)

    headers = {'content-type': 'application/json'}
    full_url = URL + "/api/campaigns"
    resp = requests.get(full_url, params=GOPHISH_KEY)
    campaigns = resp.json()

    dumped = 0 

    for camp in campaigns:
        print(type(name), type(camp["name"]))
        if name == camp["name"]:
            print(camp["name"], camp["launch_date"])
            dumped += 1
    if dumped > 0:
        print("[OK] Dumped ", dumped, " campaigns")
    else:
        print("[Error] No campaigns found to dump")
     #   ...and then dump it out:


# ------------------------------------------------------

if __name__ == '__main__':
    sys.exit(main())
